#! /bin/bash

source "/etc/conf.d/stormbyte-stage-manager.conf"

version="2.0.0"
current_folder=`pwd`
file_list=(`find "${TARBALL_FOLDER}" -type f \( -iname "*.tar.gz" -o -iname "*.tgz" -o -iname "*.tar.bz2" -o -iname "*.tbz2" -o -iname "*.tar.xz" -o -iname "*.txz" \)`)
tarball_file_fullpath=""
tarball_file=""
tarball_extension=""
tarball_output=""
tar=""
gtar="tar -I 'pigz -${COMPRESSION_LEVEL}'"
btar="tar -I 'pbzip2 -${COMPRESSION_LEVEL}'"
xtar="tar -I 'pxz -${COMPRESSION_LEVEL}eT0'"
command="$1"
arguments="$2"
tmp_folder=""
lockfile=""

function header() {
	echo "StormByte Gentoo Stage Manager Version ${version}"
	echo "Author: David C. Manuelda a.k.a StormByte <StormByte@gmail.com>"
	echo ""
}

function usage() {
	echo "This script will handle a gentoo chroot from a compressed tarball, it will mount all the needed points, chroot to it, clean, and make changes to compressed file again"
	echo "Configuration is located in /etc/conf.d/gentoo-chroot.conf"
	echo "Usage is $0 <command> <arguments>"
	echo "Where command is"
	echo " * list - will list all usable files"
	echo " * use <filename|index> - Uses a filename from list (or its index) for chrooting"
	echo " * convert <filename|index> <compression_format> - Converts to another compression format, accepted values are: gzip, bzip2 and xz"
	echo "See configuration file for more tweaking options"
}

function handleCommand() {
	# This helper will execute $1 outputting $2 as first text along with OK or ERROR if it failed
	# Example
	# executeAndHandleCommandOutput 'mount -t proc /proc "${tmp_folder}/proc"' "Mounting system..."
	echo -n "${2} ... "
	eval $1 > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		echo "OK"
	else
		echo "ERROR in command '$1'"
		cd "${current_folder}"
		exit 1
	fi
}

function checArgs() {
	if [ "$command" != "list" ] && [ "$command" != "use" ] && [ "$command" != "convert" ]; then
		usage
		exit 1
	fi
}

function checkVars() {
	local errors=0
	local re='^[1-9]$' # For checking compression level
	if [ -z "${COMPRESSION_LEVEL}" ] || ! [[ "${COMPRESSION_LEVEL}" =~ $re ]]; then
		echo "COMPRESSION_LEVEL is either empty or invalid, check if it is in a range between 1 and 9!"
		errors=1
	fi
	if [ -z "${TMPFS_SIZE}" ]; then
		echo "TMPFS_SIZE variable is not set or empty!"
		errors=1
	fi
	if [ -z "${TARBALL_FOLDER}" ]; then
		echo "TARBALL_FOLDER variable is not set or empty!"
		errors=1
	fi
	if [ "${errors}" -eq 1 ]; then
		exit 1
	fi
}

function setCompression() {
	case "$1" in
		case tar.gz)
		case tgz)
		case gzip)
		tar=${gtar}
		tarball_output="${tarball_file}.tgz"
		;;

		case tar.bz2)
		case tbz2)
		case bzip2)
		tar=${btar}
		tarball_output="${tarball_file}.tbz2"
		;;

		case tar.xz)
		case txz)
		case xz)
		tar=${xtar}
		tarball_output="${tarball_file}.txz"
		;;

		*)
		echo "Error: compression method $1 unknown"
		exit 1
	esac
}

function mountSystem() {
	handleCommand "mount -t proc /proc ${tmp_folder}/proc && mount --rbind /dev ${tmp_folder}/dev && mount --make-rslave ${tmp_folder}/dev && mount --rbind /sys ${tmp_folder}/sys && mount --make-rslave ${tmp_folder}/sys" "Mounting system structures"
}

function unmountSystem() {
	cd "${current_folder}"
	handleCommand "umount -R ${tmp_folder}/proc && umount -R ${tmp_folder}/dev && umount -R ${tmp_folder}/sys && rm -Rf {tmp_folder}/tmp/*" "Unmounting system structures and cleaning"
}

function setAndCheckFile() {
	local tarball_extension=""
	local re='^[0-9]+$'
	if [[ $arguments =~ $re ]] ; then
		tarball_file_fullpath="${file_list[$arguments]}"
	else
		tarball_file_fullpath="${TARBALL_FOLDER}/$arguments"
	fi

	if [ ! -f "${tarball_file_fullpath}" ]; then
		echo "File $tarball_file_fullpath does not exist"
		exit 1
	fi

	tarball_file="${tarball_file_fullpath%.*}"
	tarball_extension=${tarball_file##*.}
	setCompression ${tarball_extension}
	lockfile="/tmp/.${tarball_file}.${tarball_extension}"
}

function createTMPFolder() {
	tmp_folder=`mktemp -d`
}

function deleteTMPFolder() {
	rm -Rf "${tmp_folder}"
}

function mountTMPFS() {
	# If it is already mounted then we unmount it for cleaning
	if grep -qs "${tmp_folder} " /proc/mounts; then
		umount -R "${tmp_folder}"
	fi
	mkdir -p "${tmp_folder}"
	handleCommand "mount -t tmpfs -o size=${TMPFS_SIZE} tmpfs ${tmp_folder}" "Mounting tmpfs storage"
}

function unmountTMPFS() {
	cd "${current_folder}"
	handleCommand "umount -R ${tmp_folder}" "Unmounting tmpfs storage"
}

function extractArchive() {
	cd "${tmp_folder}"
	handleCommand "${tar} -xpf ${tarball_file_fullpath} --xattrs-include='*.*' --numeric-owner" "Extracting system files from ${tarball_file}"
}

function saveChanges() {
	local reply=""
	while [[ ! $reply =~ ^[YyNn]$ ]]; do
		read -p "Do you want to save the changes? [Y/N]: " -r
		reply=$REPLY
	done
	if [[ $reply =~ ^[Yy]$ ]]; then
		compressArchive
	fi
}

function compressArchive() {
	rm -Rf "${tmp_folder}"/tmp/*
	cd "${tmp_folder}"
	handleCommand "${tar} -cpf ${TARBALL_FOLDER}/${tarball_output} . --xattrs-include='*.*' --numeric-owner" "Compressing system files to ${tarball_output}"
}

function doChroot() {
	echo "Going to enter chroot, please remember to update environment with: env-update && . /etc/profile"
	chroot "${tmp_folder}" /bin/bash
}

function doList() {
	if [ -z "${file_list}" ]; then
		echo "File list is empty, check ${TARBALL_FOLDER} contents!"
		exit 1
	fi
	echo -e "File Index\tFile Name"
	for i in "${!file_list[@]}"; do
		tarball_file=`basename ${file_list[$i]}`
		echo -en "$i\t\t${tarball_file}"
		if [ -f "/tmp/.${tarball_file}" ]; then
			echo " (in use)"
		else
			echo ""
		fi
	done
}

doLock() {
	if [ -f "${lockfile}" ]; then
		echo "Another instance is running using file ${lockfile}"
		echo "If this is an error manually delete /tmp/.${lockfile} file"
		exit 1
	fi
	touch "${lockfile}"
}

doUnlock() {
	rm -f "${lockfile}"
}

function doUse() {
	setAndCheckFile
	doLock
	createTMPFolder
	mountTMPFS
	extractArchive
	mountSystem
	doChroot
	unmountSystem
	saveChanges
	unmountTMPFS
	deleteTMPFolder
	doUnlock
}

function doConvert() {
	setAndCheckFile
	doLock
	setCompression $1
	createTMPFolder
	mountTMPFS
	extractArchive
	compressArchive
	unmountTMPFS
	deleteTMPFolder
	doUnlock
}

function doInit() {
	checkArgs
	checkVars

	if [ $command = "list" ]; then
		doList
	elif [ $command = "use" ]; then
		doUse
	elif [ $command = "convert" ]; then
		doConvert
	fi
}

header
doInit

