#! /bin/bash

# Version 1.0

if [[ $# -ne 2 ]]; then
    echo "It should be used with 2 parameters: first source folder, second destination folder"
    exit 1
fi

source_folder=`realpath "$1"`
destination_folder=`realpath "$2"`

while true; do
    read -p "Do you wish to delete source files? [Y/N] " yn
    case $yn in
        [Yy]* ) delete_code=" && rm -f {}"; break;;
        [Nn]* ) delete_code=""; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

current_folder=`pwd`
cd "$source_folder"

echo "Creating folders..."
folder_count=`find . -type d | wc -l`

find . -type d | parallel --bar "mkdir -p $destination_folder/{}"
echo -e "\033[2A \033[2K \r"
echo -e "\033[2K"
echo "Creating folders... OK"
echo "Reencoding..."
find . -type f \( -iname '*.mp3' -or -iname '*.ogg' -or -iname '*.flac' -or -iname '*.wma' -or -iname '*.aac' \) | parallel --bar "ffmpeg -y -i {} -map 0 -c:v copy -c:a libfdk_aac -vbr 3 $destination_folder/{.}.m4a &> /dev/null $delete_code"
echo -e "\033[2A \033[2K \rReencoding... OK"
echo -e "\033[2K"

cd "$current_folder"
echo
echo "============================================="
echo "|               Process done!               |"
echo "============================================="


