#! /bin/bash

# Version 1.1

if [[ $# -ne 2 ]]; then
	echo "This script will convert all audio files to opus specified in parameter 1 (source folder) and will store them into specified parameter 2 destination folder maintaining folder structure."
    exit 1
fi

source_folder=`realpath "$1"`
destination_folder=`realpath "$2"`

while true; do
    read -p "Do you wish to delete source files? [Y/N] " yn
    case $yn in
        [Yy]* ) delete_code=" && rm -f {}"; break;;
        [Nn]* ) delete_code=""; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

current_folder=`pwd`
cd "$source_folder"

echo "Creating folders..."
folder_count=`find . -type d | wc -l`

find . -type d | parallel --bar "mkdir -p \"$destination_folder\"/{}"
echo -e "\033[2A \033[2K\rCreating folders... OK"
echo -e "\033[2K\rReencoding..."
find . -type f -regextype posix-extended -regex '.*\.(mp3|ogg|flac|wma|aac|wav|m4a|mp4)$' | parallel --bar "ffmpeg -y -i {} -c:a libopus -b:a 96k \"$destination_folder\"/{.}.opus &> /dev/null $delete_code"
echo -e "\033[2A \033[2K\rReencoding... OK"
echo -e "\033[2K\rCopying source opus files (not reencoded)..."
find . -type f -iname '*.opus' | parallel --bar "cp {} \"$destination_folder\"/{}"
echo -e "\033[2A \033[2K \rCopying source opus files (not reencoded)... OK"

cd "$current_folder"

echo -en "\033[2K\r"
echo -e "\033[2K\r============================================="
echo -e "\033[2K\r|               Process done!               |"
echo -e "\033[2K\r============================================="


