#! /bin/bash

# Version 1.1

if [[ $# -ne 2 ]]; then
	echo "This script will convert all video files to h265/eac3 specified in parameter 1 (source folder) and will store them into specified parameter 2 destination folder maintaining folder structure."
    exit 1
fi

source_folder=`realpath "$1"`
destination_folder=`realpath "$2"`

while true; do
    read -p "Do you wish to use animation mode? [Y/N] " yn
    case $yn in
        [Yy]* ) animation_code="-tune animation"; break;;
        [Nn]* ) animation_code=""; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

while true; do
    read -p "Do you wish to encode audio to E-AC3? [Y/N] " yn
    case $yn in
        [Yy]* ) audio_mode="eac3"; break;;
        [Nn]* ) audio_mode="copy"; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

current_folder=`pwd`
cd "$source_folder"

echo "Creating folders..."
folder_count=`find . -type d | wc -l`

find . -type d | parallel --bar "mkdir -p \"$destination_folder\"/{}"
echo -e "\033[2A \033[2K\rCreating folders... OK"
echo -e "\033[2K\rReencoding..."
find . -type f -regextype posix-extended -regex '.*\.(avi|mkv|mp4|mpg)$' | parallel --bar --jobs 1 "ffmpeg -hwaccel qsv -i {} -y -map 0 -map_metadata 0 -map_chapters 0 -c:v libx265 -profile:v main10 -level:v 5.1 -x265-params \"level=5.1:aq-mode=3\" -pix_fmt yuv420p10le -maxrate:v 5M -bufsize:v 200M $animation_code -c:a $audio_mode -c:s copy \"$destination_folder\"/{.}.mkv &> /dev/null"
echo -e "\033[2A \033[2K\rReencoding... OK"

cd "$current_folder"

echo -en "\033[2K\r"
echo -e "\033[2K\r============================================="
echo -e "\033[2K\r|               Process done!               |"
echo -e "\033[2K\r============================================="


